import Head from "next/head";
import Link from "next/link";

export default function Home() {
  return (
    <div>
      <Head>
        <title>Soberout</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <header>
        <nav>
          <ul>
            <li>
              <Link href="/events">Events</Link>
            </li>
            <li>
              <Link href="/members">Members</Link>
            </li>
          </ul>
        </nav>
      </header>
      <main>
        <h1>Main Home Page</h1>
      </main>
    </div>
  );
}
